const STATES = {
    NORMAL: "NORMAL",
    LOADING: "LOADING",
    WRITING_MESSAGE: "WRITING_MESSAGE",
    TYPE_NAME: "TYPENAME",
    CHOOSE_GENDER: "CHOSEGENDER",
    CHOOSE_AGE: "CHOSEAGE"
};

module.exports = STATES;
